require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IncomeStatementsController do

  # This should return the minimal set of attributes required to create a valid
  # IncomeStatement. As you add validations to IncomeStatement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IncomeStatementsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all income_statements as @income_statements" do
      income_statement = IncomeStatement.create! valid_attributes
      get :index, {}, valid_session
      assigns(:income_statements).should eq([income_statement])
    end
  end

  describe "GET show" do
    it "assigns the requested income_statement as @income_statement" do
      income_statement = IncomeStatement.create! valid_attributes
      get :show, {:id => income_statement.to_param}, valid_session
      assigns(:income_statement).should eq(income_statement)
    end
  end

  describe "GET new" do
    it "assigns a new income_statement as @income_statement" do
      get :new, {}, valid_session
      assigns(:income_statement).should be_a_new(IncomeStatement)
    end
  end

  describe "GET edit" do
    it "assigns the requested income_statement as @income_statement" do
      income_statement = IncomeStatement.create! valid_attributes
      get :edit, {:id => income_statement.to_param}, valid_session
      assigns(:income_statement).should eq(income_statement)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new IncomeStatement" do
        expect {
          post :create, {:income_statement => valid_attributes}, valid_session
        }.to change(IncomeStatement, :count).by(1)
      end

      it "assigns a newly created income_statement as @income_statement" do
        post :create, {:income_statement => valid_attributes}, valid_session
        assigns(:income_statement).should be_a(IncomeStatement)
        assigns(:income_statement).should be_persisted
      end

      it "redirects to the created income_statement" do
        post :create, {:income_statement => valid_attributes}, valid_session
        response.should redirect_to(IncomeStatement.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved income_statement as @income_statement" do
        # Trigger the behavior that occurs when invalid params are submitted
        IncomeStatement.any_instance.stub(:save).and_return(false)
        post :create, {:income_statement => {  }}, valid_session
        assigns(:income_statement).should be_a_new(IncomeStatement)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        IncomeStatement.any_instance.stub(:save).and_return(false)
        post :create, {:income_statement => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested income_statement" do
        income_statement = IncomeStatement.create! valid_attributes
        # Assuming there are no other income_statements in the database, this
        # specifies that the IncomeStatement created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        IncomeStatement.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => income_statement.to_param, :income_statement => { "these" => "params" }}, valid_session
      end

      it "assigns the requested income_statement as @income_statement" do
        income_statement = IncomeStatement.create! valid_attributes
        put :update, {:id => income_statement.to_param, :income_statement => valid_attributes}, valid_session
        assigns(:income_statement).should eq(income_statement)
      end

      it "redirects to the income_statement" do
        income_statement = IncomeStatement.create! valid_attributes
        put :update, {:id => income_statement.to_param, :income_statement => valid_attributes}, valid_session
        response.should redirect_to(income_statement)
      end
    end

    describe "with invalid params" do
      it "assigns the income_statement as @income_statement" do
        income_statement = IncomeStatement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IncomeStatement.any_instance.stub(:save).and_return(false)
        put :update, {:id => income_statement.to_param, :income_statement => {  }}, valid_session
        assigns(:income_statement).should eq(income_statement)
      end

      it "re-renders the 'edit' template" do
        income_statement = IncomeStatement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IncomeStatement.any_instance.stub(:save).and_return(false)
        put :update, {:id => income_statement.to_param, :income_statement => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested income_statement" do
      income_statement = IncomeStatement.create! valid_attributes
      expect {
        delete :destroy, {:id => income_statement.to_param}, valid_session
      }.to change(IncomeStatement, :count).by(-1)
    end

    it "redirects to the income_statements list" do
      income_statement = IncomeStatement.create! valid_attributes
      delete :destroy, {:id => income_statement.to_param}, valid_session
      response.should redirect_to(income_statements_url)
    end
  end

end
